noonDashboard.MVC/Controllers/ProductBrandController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using noon.Application.Contract;
using noon.Application.Services.ProductBrandServices;
using noon.Domain.Models;
using noon.DTO.ProductDTO;
using noon.Infrastructure.Repositorys;
using System.Data;

namespace noonDashboard.MVC.Controllers
{
    [Authorize(Roles = "admin ")]
    public class ProductBrandController : Controller
    {
        private readonly IProductBrandServices brandServices;

        public ProductBrandController(IProductBrandServices brandServices)
        {
            this.brandServices = brandServices;
        }
        public async Task <IActionResult> Index()
        {
            var data = brandServices.GetAll();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductBrandDTO brandDto)
        {
            if (ModelState.IsValid)
            {
                brandServices.Create(brandDto);
                return RedirectToAction("index");
            }
            return View(brandDto);
        }

        public async Task< IActionResult> Edit(int id)
        {
            var data = await brandServices.GetById(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(ProductBrandDTO brandDTO)
        {
            if (ModelState.IsValid)
            {
                brandServices.Update(brandDTO);
                return RedirectToAction("index");
            }
            return View(brandDTO);
        }

        public async Task<IActionResult> Details(int id)
        {
            var data = await brandServices.GetById(id);
            return View(data);
        }

        public IActionResult Delete(int id)
        {
            brandServices.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

noonDashboard.MVC/Views/ProductBrand/Create.cshtml
@model ProductBrandDTO
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-controller="ProductBrand" asp-action="Create" class="form-group" method="post">
    <div class="m-2">
        <label asp-for="name" class="py-2">Brand Name</label>
        <input class="form-control" type="text" asp-for="name" />
        <div class="m-auto text-center">
            <span asp-validation-for="name" class="text-danger shadow-sm "></span>
        </div>
    </div>

    <div class="m-2">
        <label asp-for="logoUrl" class="py-2">
            Logo Url
        </label>
        <input class="form-control" type="text" asp-for="logoUrl" />
        <div class="m-auto text-center">
            <span asp-validation-for="logoUrl" class="text-danger shadow-sm"></span>
        </div>
    </div>


    


    




    <div style="margin-top:2rem">
        <input type="submit" class="btn btn-primary my-5 border shadow-5 px-5 py-3 rounded-3" value="Create Brand" />
        <a asp-action="index" type="button" class="btn btn-info " style="margin-left:2rem">Back to list</a>
    </div>


</form>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

noonDashboard.MVC/Views/ProductBrand/Details.cshtml
@model ProductBrandDTO
@{
    ViewData["Title"] = "Details";
}

<div class="row " style="width:75%; margin:auto ">
    <div class="p-5 card col-sd-12 col-md-7">
        <img src="@Model.logoUrl" class="card-img-top" alt="..." style="width:100%">
        <div class="card-body mb-3">
            <h4 class="card-title">Brand Name : @Model.name</h4>
        </div>

    </div>
</div>
<div style="width:60%; margin:auto ">
    <a asp-action="Index" class="btn btn-primary m-5 w-25" style="width:25%; margin-left:40px">Back to list</a>
    </div>

noonDashboard.MVC/Views/ProductBrand/Edit.cshtml
@model ProductBrandDTO
@{
    ViewData["Title"] = "Edit";
}

<form asp-action="Edit" class="form-group" method="post">

    <div class="m-2">
        <label asp-for="name" class="py-2">Brand Name</label>
        <input class="form-control" type="text" asp-for="name" />
        <div class="m-auto text-center">
            <span asp-validation-for="name" class="text-danger shadow-sm "></span>
        </div>
    </div>

    <div class="m-2">
        <label asp-for="logoUrl" class="py-2">
            Brand Logo Url
        </label>
        <input class="form-control" type="text" asp-for="logoUrl" />
        <div class="m-auto text-center">
            <span asp-validation-for="logoUrl" class="text-danger shadow-sm"></span>
        </div>
    </div>

    <div class="d-flex justify-content-center align-content-center  my-3">
        <input type="submit" class="btn btn-success my-5 border shadow-5 px-5 py-3 rounded-3" value="Save" />
    </div>
</form>

<a asp-action="Index" class="btn btn-primary ">Back to list</a>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

noonDashboard.MVC/Views/ProductBrand/Index.cshtml
@model List<ProductBrandDTO>
@{
    ViewData["Title"] = "Index";
}



<h1 class="d-flex justify-content-center text-success">Product Brands</h1>



<style>
    th {
        text-align: center !important;
    }
    
</style>


@section BootstrapSelect{
    <link href="~/Layout/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Layout/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css" rel="stylesheet" />
}

<a asp-controller="ProductBrand" asp-action="Create" class="btn btn-primary ">Create New Product Brand</a>

<br />
<br />
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>Product Brands</h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable text-center font-weight-bold">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Details</th>
                                    <th>Update</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.id</td>
                                        <td>@item.name</td>
                                        <td><a asp-controller="ProductBrand" asp-action="Details" asp-route-id="@item.id" class="btn btn-success">Details</a></td>
                                        <td><a asp-controller="ProductBrand" asp-action="Edit" asp-route-id="@item.id" class="btn btn-warning">Update</a></td>
                                        <td><a asp-controller="ProductBrand" asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@section DataTableScripts{

    <script src="~/Layout/plugins/jquery-datatable/jquery.dataTables.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>


    <script src="~/Layout/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/buttons.flash.min.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
    <script src="~/Layout/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>



    <script>
        $(function () {
            $('.js-basic-example').DataTable({
                responsive: true,
                paging: true,
                pageLength: 5,
                bSort: true,
                bFilter: true,
                bLengthChange: false,
                //bInfo: false,
                lengthMenu: [[3, 5, 10, 25, 50, -1], [3, 5, 10, 25, 50, "All"]],

            });



            var table = $('.js-basic-example').DataTable();

            new $.fn.dataTable.Buttons(table, {
                buttons: [
                    'copy', 'excel', 'pdf', 'csv', 'print'
                ]
            });

            table.buttons().container()
                .appendTo($('.col-sm-6:eq(0)', table.table().container()));


        });

    </script>
}